# Site settings
title: hutt
email: mail@hutt.wtf
description: Website by hutt
permalink: /p/:title.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hutt.wtf" # the base hostname & protocol for your site
twitter_username: Der_Hutt
github_username:  77u4
copyright_notice: 'Copyright &copy; 2014 - 2015 @<a href="http://twitter.com/{{ site.twitter_username }}"> {{ site.twitter_username }} </a>'
pgp: "0x9BAD2EA15BCF1DFF"

# Build settings
markdown: kramdown
