# Site settings
title: hutt
email: mail@hutt.wtf
description: > # hutt's official website
baseurl: ""
url: "http://hutt.wtf"
copyright: "&copy; 2015 hutt"

#Social
blog_url: "http://jh0.eu"
twitter_username: Der_Hutt
github_username: 77u4

# Build settings
markdown: kramdown
